// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnW6NOcZb5ujNnQaKHWi3hiXR_lutzaMc',
    appId: '1:251558571470:web:81569825417432da268f9f',
    messagingSenderId: '251558571470',
    projectId: 'fruitsmugahed-dfdaa',
    authDomain: 'fruitsmugahed-dfdaa.firebaseapp.com',
    storageBucket: 'fruitsmugahed-dfdaa.firebasestorage.app',
    measurementId: 'G-XQ83KHF03T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzcB0cilUOikQqfA2xaCHej4WRBg9WrM',
    appId: '1:251558571470:android:5c3c7c0bcfcd022c268f9f',
    messagingSenderId: '251558571470',
    projectId: 'fruitsmugahed-dfdaa',
    storageBucket: 'fruitsmugahed-dfdaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBg1rcCa29fgZIz9X2xHB-cQnNNFXu0uc',
    appId: '1:251558571470:ios:38db21c4b9690c0a268f9f',
    messagingSenderId: '251558571470',
    projectId: 'fruitsmugahed-dfdaa',
    storageBucket: 'fruitsmugahed-dfdaa.firebasestorage.app',
    iosBundleId: 'com.example.fruitsmugahed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBg1rcCa29fgZIz9X2xHB-cQnNNFXu0uc',
    appId: '1:251558571470:ios:38db21c4b9690c0a268f9f',
    messagingSenderId: '251558571470',
    projectId: 'fruitsmugahed-dfdaa',
    storageBucket: 'fruitsmugahed-dfdaa.firebasestorage.app',
    iosBundleId: 'com.example.fruitsmugahed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnW6NOcZb5ujNnQaKHWi3hiXR_lutzaMc',
    appId: '1:251558571470:web:5117c3332721eaac268f9f',
    messagingSenderId: '251558571470',
    projectId: 'fruitsmugahed-dfdaa',
    authDomain: 'fruitsmugahed-dfdaa.firebaseapp.com',
    storageBucket: 'fruitsmugahed-dfdaa.firebasestorage.app',
    measurementId: 'G-NVGW56Z96R',
  );
}
